// ******************************************************************************************
// * This project is licensed under the GNU Affero GPL v3. Copyright © 2014 A3Wasteland.com *
// ******************************************************************************************
//	@file Version: 1.0
//	@file Name: mission_APC.sqf
//	@file Author: [404] Deadbeat, [404] Costlyy, AgentRev
//	@file Created: 08/12/2012 15:19

if (!isServer) exitwith {};
#include "mainMissionDefines.sqf";

private ["_vehicleClass", "_nbUnits"];

_setupVars =
{
	_vehicleClass =
	[
		"B_APC_Wheeled_01_cannon_F",
		"O_APC_Wheeled_02_rcws_F",
		"I_APC_Wheeled_03_cannon_F",
		"B_APC_Tracked_01_rcws_F",
		"O_APC_Tracked_02_cannon_F",
		"I_APC_tracked_03_cannon_F",
		"B_APC_Tracked_01_AA_F",
		"O_APC_Tracked_02_AA_F",
		"gm_gc_army_brdm2_oli",
		"gm_gc_army_brdm2_ols",
		"gm_gc_army_brdm2_olw",
		"gm_gc_army_brdm2_un",
		"gm_gc_army_brdm2_wdl",
		"gm_gc_army_brdm2_win",
		"gm_gc_army_brdm2um_oli",
		"gm_gc_army_brdm2um_ols",
		"gm_gc_army_brdm2um_olw",
		"gm_gc_army_brdm2um_un",
		"gm_gc_army_brdm2um_wdl",
		"gm_gc_army_brdm2um_win",
		"gm_gc_army_btr60pa_oli",
		"gm_gc_army_btr60pa_ols",
		"gm_gc_army_btr60pa_olw",
		"gm_gc_army_btr60pa_un",
		"gm_gc_army_btr60pa_wdl",
		"gm_gc_army_btr60pa_win",
		"gm_gc_army_btr60pb_oli",
		"gm_gc_army_btr60pb_ols",
		"gm_gc_army_btr60pb_olw",
		"gm_gc_army_btr60pb_un",
		"gm_gc_army_btr60pb_wdl",
		"gm_gc_army_btr60pb_win",
		"gm_gc_army_btr60pu12_oli",
		"gm_gc_army_btr60pu12_ols",
		"gm_gc_army_btr60pu12_olw",
		"gm_gc_army_btr60pu12_un",
		"gm_gc_army_btr60pu12_wdl",
		"gm_gc_army_btr60pu12_win",
		"gm_gc_army_bmp1sp2_oli",
		"gm_gc_army_bmp1sp2_ols",
		"gm_gc_army_bmp1sp2_olw",
		"gm_gc_army_bmp1sp2_un",
		"gm_gc_army_bmp1sp2_wdl",
		"gm_gc_army_bmp1sp2_win",
		"gm_gc_army_pt76b_oli",
		"gm_gc_army_pt76b_ols",
		"gm_gc_army_pt76b_olw",
		"gm_gc_army_pt76b_un",
		"gm_gc_army_pt76b_wdl",
		"gm_gc_army_pt76b_win",
		"gm_pl_army_brdm2_oli",
		"gm_pl_army_brdm2_ols",
		"gm_pl_army_brdm2_olw",
		"gm_pl_army_brdm2_inv",
		"gm_pl_army_ot64a_oli",
		"gm_pl_army_ot64a_ols",
		"gm_pl_army_ot64a_olw",
		"gm_pl_army_ot64a_inv",
		"gm_pl_army_bmp1sp2_oli",
		"gm_pl_army_bmp1sp2_ols",
		"gm_pl_army_bmp1sp2_olw",
		"gm_pl_army_bmp1sp2_inv",
		"gm_pl_army_pt76b_oli",
		"gm_pl_army_pt76b_ols",
		"gm_pl_army_pt76b_olw",
		"gm_pl_army_pt76b_inv",
		"gm_pl_army_zsu234v1_oli",
		"gm_pl_army_zsu234v1_ols",
		"gm_pl_army_zsu234v1_olw",
		"gm_pl_army_zsu234v1_inv",
		"gm_gc_army_zsu234v1_oli",
		"gm_gc_army_zsu234v1_ols",
		"gm_gc_army_zsu234v1_olw",
		"gm_gc_army_zsu234v1_un",
		"gm_gc_army_zsu234v1_wdl",
		"gm_gc_army_zsu234v1_win",
		"gm_dk_army_bpz2a0_un",
		"gm_dk_army_bpz2a0_wdl",
		"gm_dk_army_bpz2a0_win",
		"gm_dk_army_bpz2a0_des",
		"gm_dk_army_bpz2a0_tan",
		"gm_dk_army_m113a1dk_apc_un",
		"gm_dk_army_m113a1dk_apc_wdl",
		"gm_dk_army_m113a1dk_apc_win",
		"gm_dk_army_m113a1dk_apc_des",
		"gm_dk_army_m113a1dk_apc_tan",
		"gm_dk_army_m113a1dk_command_un",
		"gm_dk_army_m113a1dk_command_wdl",
		"gm_dk_army_m113a1dk_command_win",
		"gm_dk_army_m113a1dk_command_des",
		"gm_dk_army_m113a1dk_command_tan",
		"gm_dk_army_m113a1dk_engineer_un",
		"gm_dk_army_m113a1dk_engineer_wdl",
		"gm_dk_army_m113a1dk_engineer_win",
		"gm_dk_army_m113a1dk_engineer_des",
		"gm_dk_army_m113a1dk_engineer_tan",
		"gm_dk_army_m113a1dk_medic_un",
		"gm_dk_army_m113a1dk_medic_wdl",
		"gm_dk_army_m113a1dk_medic_win",
		"gm_dk_army_m113a1dk_medic_des",
		"gm_dk_army_m113a1dk_medic_tan",
		"gm_dk_army_m113a2dk_win",
		"gm_dk_army_m113a2dk_wdl",
		"gm_dk_army_m113a2dk_un",
		"gm_ge_army_marder1a1a_des",
		"gm_ge_army_marder1a1a_oli",
		"gm_ge_army_marder1a1a_ols",
		"gm_ge_army_marder1a1a_olw",
		"gm_ge_army_marder1a1a_trp",
		"gm_ge_army_marder1a1a_un",
		"gm_ge_army_marder1a1a_wdl",
		"gm_ge_army_marder1a1a_win",
		"gm_ge_army_marder1a1a_wiw",
		"gm_ge_army_marder1a1plus_des",
		"gm_ge_army_marder1a1plus_oli",
		"gm_ge_army_marder1a1plus_ols",
		"gm_ge_army_marder1a1plus_olw",
		"gm_ge_army_marder1a1plus_trp",
		"gm_ge_army_marder1a1plus_un",
		"gm_ge_army_marder1a1plus_wdl",
		"gm_ge_army_marder1a1plus_win",
		"gm_ge_army_marder1a1plus_wiw",
		"gm_ge_army_marder1a2_des",
		"gm_ge_army_marder1a2_oli",
		"gm_ge_army_marder1a2_ols",
		"gm_ge_army_marder1a2_olw",
		"gm_ge_army_marder1a2_trp",
		"gm_ge_army_marder1a2_un",
		"gm_ge_army_marder1a2_wdl",
		"gm_ge_army_marder1a2_win",
		"gm_ge_army_marder1a2_wiw",
		"gm_ge_army_fuchsa0_command_des",
		"gm_ge_army_fuchsa0_command_oli",
		"gm_ge_army_fuchsa0_command_ols",
		"gm_ge_army_fuchsa0_command_olw",
		"gm_ge_army_fuchsa0_command_trp",
		"gm_ge_army_fuchsa0_command_un",
		"gm_ge_army_fuchsa0_command_wdl",
		"gm_ge_army_fuchsa0_command_win",
		"gm_ge_army_fuchsa0_command_wiw",
		"gm_ge_army_fuchsa0_engineer_des",
		"gm_ge_army_fuchsa0_engineer_oli",
		"gm_ge_army_fuchsa0_engineer_ols",
		"gm_ge_army_fuchsa0_engineer_olw",
		"gm_ge_army_fuchsa0_engineer_trp",
		"gm_ge_army_fuchsa0_engineer_un",
		"gm_ge_army_fuchsa0_engineer_wdl",
		"gm_ge_army_fuchsa0_engineer_win",
		"gm_ge_army_fuchsa0_engineer_wiw",
		"gm_ge_army_fuchsa0_reconnaissance_des",
		"gm_ge_army_fuchsa0_reconnaissance_oli",
		"gm_ge_army_fuchsa0_reconnaissance_ols",
		"gm_ge_army_fuchsa0_reconnaissance_olw",
		"gm_ge_army_fuchsa0_reconnaissance_trp",
		"gm_ge_army_fuchsa0_reconnaissance_un",
		"gm_ge_army_fuchsa0_reconnaissance_wdl",
		"gm_ge_army_fuchsa0_reconnaissance_win",
		"gm_ge_army_fuchsa0_reconnaissance_wiw",
		"gm_ge_army_luchsa1_oli",
		"gm_ge_army_luchsa1_ols",
		"gm_ge_army_luchsa1_olw",
		"gm_ge_army_luchsa2_des",
		"gm_ge_army_luchsa2_oli",
		"gm_ge_army_luchsa2_ols",
		"gm_ge_army_luchsa2_olw",
		"gm_ge_army_luchsa2_trp",
		"gm_ge_army_luchsa2_un",
		"gm_ge_army_luchsa2_wdl",
		"gm_ge_army_luchsa2_win",
		"gm_ge_army_luchsa2_wiw",
		"gm_ge_army_bpz2a0_des",
		"gm_ge_army_bpz2a0_oli",
		"gm_ge_army_bpz2a0_ols",
		"gm_ge_army_bpz2a0_olw",
		"gm_ge_army_bpz2a0_trp",
		"gm_ge_army_bpz2a0_un",
		"gm_ge_army_bpz2a0_wdl",
		"gm_ge_army_bpz2a0_win",
		"gm_ge_army_bpz2a0_wiw",
		"gm_ge_army_gepard1a1_des",
		"gm_ge_army_gepard1a1_oli",
		"gm_ge_army_gepard1a1_ols",
		"gm_ge_army_gepard1a1_olw",
		"gm_ge_army_gepard1a1_trp",
		"gm_ge_army_gepard1a1_un",
		"gm_ge_army_gepard1a1_wdl",
		"gm_ge_army_gepard1a1_win",
		"gm_ge_army_gepard1a1_wiw",
		"gm_ge_army_m113a1g_apc_des",
		"gm_ge_army_m113a1g_apc_oli",
		"gm_ge_army_m113a1g_apc_ols",
		"gm_ge_army_m113a1g_apc_olw",
		"gm_ge_army_m113a1g_apc_trp",
		"gm_ge_army_m113a1g_apc_un",
		"gm_ge_army_m113a1g_apc_wdl",
		"gm_ge_army_m113a1g_apc_win",
		"gm_ge_army_m113a1g_apc_wiw",
		"gm_ge_army_m113a1g_apc_milan_des",
		"gm_ge_army_m113a1g_apc_milan_oli",
		"gm_ge_army_m113a1g_apc_milan_ols",
		"gm_ge_army_m113a1g_apc_milan_olw",
		"gm_ge_army_m113a1g_apc_milan_trp",
		"gm_ge_army_m113a1g_apc_milan_un",
		"gm_ge_army_m113a1g_apc_milan_wdl",
		"gm_ge_army_m113a1g_apc_milan_win",
		"gm_ge_army_m113a1g_apc_milan_wiw",
		"gm_ge_army_m113a1g_command_des",
		"gm_ge_army_m113a1g_command_oli",
		"gm_ge_army_m113a1g_command_ols",
		"gm_ge_army_m113a1g_command_olw",
		"gm_ge_army_m113a1g_command_trp",
		"gm_ge_army_m113a1g_command_un",
		"gm_ge_army_m113a1g_command_wdl",
		"gm_ge_army_m113a1g_command_win",
		"gm_ge_army_m113a1g_command_wiw",
		"gm_ge_army_m113a1g_medic"
	] call BIS_fnc_selectRandom;

	_missionType = switch (true) do
	{
		case ({_vehicleClass isKindOf _x} count ["B_APC_Tracked_01_AA_F", "O_APC_Tracked_02_AA_F"] > 0): { "Anti Aircraft Vehicle" };
		case (_vehicleClass isKindOf "Tank_F"):                                                          { "Infantry Fighting Vehicle" };
		default                                                                                          { "Armored Personnel Carrier" };
	};

	_locationsArray = MissionSpawnMarkers;

	_nbUnits = if (missionDifficultyHard) then { AI_GROUP_LARGE } else { AI_GROUP_MEDIUM };
};

_this call mission_VehicleCapture;
